title: Jolly Good Code's Blog
url: http://jollygoodcode.com/blog
exclude: [vendor]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
